version: '3'
#### NGINX GATEWAY
services:
  web:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_PORT}:80"
    links:
      - app
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/vhosts.conf:/etc/nginx/conf.d/default.conf

#### PHP APPLICATION
  app:
    image: ${APP_NAME}:${APP_VERSION}
    build:
      context: ./
      args:
        pkg: ${APP_APT_PACKAGES}
        ext: ${APP_PHP_EXTENSIONS}
    links:
      - db
      - cache
    restart: always
    volumes:
      - ./app:/app
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_STAGE
      - APP_NAME
      - APP_VERSION

#### MYSQL DATABASE
  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - mysql_data:/data
    working_dir: /data
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

#### REDIS CACHE
  cache:
    image: redis:${REDIS_VERSION}
    restart: always
    volumes:
      - ./conf/redis.conf:/etc/redis.conf
      - redis_data:/data
    command: redis-server /etc/redis.conf

volumes:
  mysql_data:
  redis_data:

